name: flux_core
description: "Flux Framework Core — A lightweight Flutter framework core with abstract UI interfaces."
version: 1.0.2
publish_to: 'none'

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  # Networking
  dio: ^5.8.0+1

  # State Management & Routing
  get: ^4.7.2

  # Storage
  shared_preferences: ^2.5.3

  # Logging
  logger: ^2.6.1

  # JSON
  json_annotation: ^4.9.0

  # Date/Time
  intl: ^0.20.2
  ntp: ^2.0.0

  # Screen Adaptation
  flutter_screenutil: ^5.9.3

  # Encryption & UUID
  crypto: ^3.0.6
  uuid: ^4.5.1

  # Device
  device_info_plus: ^11.5.0
  package_info_plus: ^8.3.0
  android_id: ^0.3.6
  flutter_keychain_plus: ^0.0.4

  # Flux Common Code
  badges: ^3.2.0
  permission_handler: ^12.0.3
  lottie: ^3.3.3
  easy_refresh: ^3.5.0
  loading_animation_widget: ^1.3.0
  fluttertoast: ^9.1.0

  # Flux Gen
  app_settings: ^7.0.0
  url_launcher: ^6.3.2
  json_serializable: ^6.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.8.0
  build_runner: any

flutter:
  uses-material-design: true